#!/bin/bash
find . -type f -name '*.gif' -exec sh -c '
  for file; do
    printf "%s\n" "${file##*/}" | sed "s/\.gif$//"
  done
' sh {} + | sort -f | awk '{print tolower($0), $0}' | sort -k 1,1 | cut -d" " -f2

