#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Create HAProxy configuration
CONFIG_TEXT="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.207.212.172:80 check
    server web-02 18.210.13.214:80 check
"

# Backup original config if it exists
if [ -f /etc/haproxy/haproxy.cfg ]; then
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
fi

# Write new config
echo "$CONFIG_TEXT" > /etc/haproxy/haproxy.cfg

# Start HAProxy
service haproxy restart
